### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by amontesr** [ConservationInternational/Wild.ID#2]
Hi! I've been having an issue installing WildID on my mac. I've used it for a while now and all of the sudden it stopped working. I tried to uninstall the program and re-installing, even older versions, but nothing seems to work. I wonder if this issue has to do with my JAVA version? 

Thanks in advanced for your attention.

**Comment by Beremelek** [comment]
Hello. I have the same problem here... I'm using macOS Catalina. WildID is installed but doesn't launch, the icon just sits on the application belt and doesn't respond. I also tried both the latest and older versions - no difference. Tried also uninstalling the software, restarting the laptop - no difference. Only one version is installed at the same time. 
Any advice will be much appreciated!

**Comment by klinucsd** [comment]
Could you please check the log file at /Applications/Wild.ID.app/Contents/Java/WildID.log to see if there are any error messages?  

If no error message is found, could you please use the following command to run Wild.ID from your terminal and then watch if there are any error messages in the terminal:

/Applications/Wild.ID.app/Contents/MacOS/Wild.ID 

This may help to identify the reason of the problem.

**Comment by Beremelek** [comment]
Dear klinucsd,
Thank you for your fast and helpful answer!

- There was a java error: "2020-06-23 22:24:31,394 ERROR 0 org.wildid.app.Util [JavaFX Application Thread] Initial SessionFactory creation failed.java.lang.RuntimeException: Could not start MySQL."
- I downloaded JDK and JRE which removed this error (java log is empty) but the wildID still doesn't launch.

Currently, the terminal output states:
- "Caused by: java.io.IOException: Cannot run program "/Applications/Wild.ID.app/Contents/Java/mysql-mxj/bin/mysqld": error=86, Bad CPU type in executable"
- Oracle Help Center recommends: "Action: Inspect the internal exception and check the Java manuals.". 

I couldn't find any easy-to-follow guidelines how to do that. Is that something advanced to do? I'm a standard-level laptop user...

**Comment by klinucsd** [comment]
Hi Beremelek,

Thank you so much for helping us to figure out the problem.  Actually the problem is much serious than we expected. Started from macOS Catalina,  Mac stopped supporting 32 bits software. Unfortunately the embedded MySQL version used in Wild.ID is a 32 bits application. It looks like this MySQL couldn't be started from your machine.  Another bad news is Oracle doesn't provide any free license for the latest embedded MySQL. This situation would enforce us to change the database.  Sorry for the inconvenience.

**Comment by amontesr** [comment]
Hi all,

The only solution I found was to downgrade to Mojave as neither of the things I tried in Catalina worked. If you need the App urgently I think this might be the most effective solution for now.

Best,

Andrés Montes


El 23/06/2020, a la(s) 8:55 p. m., Kai Lin <notifications@github.com> escribió:

﻿

Hi Beremelek,

Hola Thank you so much for helping us to figure out the problem. Actually the problem is much serious than we expected. Started from macOS Catalina, Mac stopped supporting 32 bits software. Unfortunately the embedded MySQL version used in Wild.ID is a 32 bits application. It looks like this MySQL couldn't be started from your machine. Another bad news is Oracle doesn't provide any free license for the latest embedded MySQL. This situation would enforce us to change the database. Sorry for the inconvenience.

**Comment by Beremelek** [comment]
Hello all,

Thank you so much for your fast support and the detailed explanation of the issue. I thought it might be beyond the simple "click-here-and-it's-fixed" methods... It's not a big problem, though. I'll either use another machine in my lab, revert from macOS Catalina (as suggested), or try installing a virtual machine program.

Best wishes to the whole wildID team!

**Comment by klinucsd** [comment]
Hi Beremelek and Andrés,

I packed Wild.ID with a 64-bit version MySQL for Mac. It will automatically check your platform and use the appropriate  MySQL version.   You can download and try it from this URL:  [http://twsa.ucsd.edu:8080/Wild.ID-0.9.32.dmg](url) . Please let me know if it works for you. 

Thanks

**Comment by Beremelek** [comment]
Hi klinucsd,

The program has finally launched! :) Thank you so much for your time and the excellent help. I'm looking forward to trying out the software. Strangely, I had to copy&paste the link you provided to start the download. Just clicking on the link would open a blank "ConservationInternational/Wild.ID" page. 

Best greetings,
Berenika Mioduszewska

**Comment by vnandigam** [comment]
Wild.ID with a 64-bit version MySQL for Mac. Automatically checks your platform and use the appropriate MySQL version. Download is at https://github.com/ConservationInternational/Wild.ID/releases/tag/0.9.32
